steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['clean', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/location-data-278514/location-data-image:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/location-data-image:$COMMIT_SHA || exit 0
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=location-data-cluster'
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" == "master" ]] && \
        gcloud container clusters get-credentials location-data-cluster; \
        kubectl set image deployment/location-data-service \
        location-data-image=gcr.io/location-data-278514/location-data-image:$COMMIT_SHA || exit 0
